// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetGlz(arg1:string):Promise<any>;

export function GetLocal(arg1:string):Promise<any>;

export function GetPd(arg1:string):Promise<any>;

export function Init():Promise<boolean>;

export function Test():Promise<any>;
