// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SelfID() {
  return window['go']['valorant']['Client']['SelfID']();
}

export function GetGlz(arg1) {
  return window['go']['valorant']['Client']['GetGlz'](arg1);
}

export function GetLocal(arg1) {
  return window['go']['valorant']['Client']['GetLocal'](arg1);
}

export function GetPd(arg1) {
  return window['go']['valorant']['Client']['GetPd'](arg1);
}

export function Init() {
  return window['go']['valorant']['Client']['Init']();
}
