// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetCurrentVersion() {
  return window['go']['valorant']['Client']['GetCurrentVersion']();
}

export function GetGlz(arg1) {
  return window['go']['valorant']['Client']['GetGlz'](arg1);
}

export function GetPd(arg1) {
  return window['go']['valorant']['Client']['GetPd'](arg1);
}

export function GetShared(arg1) {
  return window['go']['valorant']['Client']['GetShared'](arg1);
}

export function PerformSelfUpdate() {
  return window['go']['valorant']['Client']['PerformSelfUpdate']();
}

export function PutPd(arg1, arg2) {
  return window['go']['valorant']['Client']['PutPd'](arg1, arg2);
}

export function Run() {
  window['go']['valorant']['Client']['Run']();
}

export function GetLatestVersion() {
  return window['go']['valorant']['Client']['GetLatestVersion']();
}

export function GetLocal(arg1) {
  return window['go']['valorant']['Client']['GetLocal'](arg1);
}

export function SelfID() {
  return window['go']['valorant']['Client']['SelfID']();
}

export function Stop() {
  window['go']['valorant']['Client']['Stop']();
}
