// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetPd(arg1:string):Promise<any>;

export function GetShared(arg1:string):Promise<any>;

export function Run():void;

export function SelfID():Promise<any>;

export function Stop():void;

export function GetCurrentVersion():Promise<string>;

export function GetLatestVersion():Promise<any>;

export function GetLocal(arg1:string):Promise<any>;

export function GetGlz(arg1:string):Promise<any>;

export function PerformSelfUpdate():Promise<boolean>;

export function PutPd(arg1:string,arg2:string):Promise<any>;
