// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function SaveLog(arg1, arg2) {
  window['go']['utils']['Utility']['SaveLog'](arg1, arg2);
}
